spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/account?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: haifeng
    password: haifeng
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
server:
  port: 7088


security:
  oauth2:
    resource:
      token-info-uri : http://localhost:7080/oauth/check_token
    client:
      client-id: client_1
      client-secret: 123456
