version: '2'

services:
  db:
    #window,linux用这里
    image: mysql:5.7
    #only use for linux and mac
    ports:
      - "3306"
    volumes:
      - ~/dockerShare/mysql/svae:/var/lib/mysql
    env_file:
      - ./env/mysql.env
    environment:
      - "TZ=Asia/Shanghai"
  gateway:
    build: ./gateway/
    image: haifeng/gateway:latest
    ports:
      - "8080:8080"
    links:
      - db:db
    env_file:
      - ./env/mysql.env
      - ./env/gateway.env
    environment:
      TZ: Asia/Shanghai
  oauthserver:
    build: ./oauthserver/
    image: haifeng/oauthserver:latest
    links:
      - db:db
    env_file:
      - ./env/mysql.env
    environment:
      TZ: Asia/Shanghai
  account:
    build: ./account/
    image: haifeng/account:latest
    links:
      - db:db
    env_file:
      - ./env/mysql.env
    environment:
      TZ: Asia/Shanghai