spring:
   profiles: default
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  host:
      socket-timeout-millis: 30000
  routes:
    authorized:
      path: /oauth/**
      url:  http://authserver:9999/uaa/oauth
    account:
      path: /accounts/**
      url: http://account:8090/accounts
    resource:
      path: /resource/**
      url: http://resource:9000/resource
logging:
  level:
    org.springframework.cloud.netflix.zuul.EnableZuulProxy: DEBUG

